- name: play level varibles
  hosts: local
  connection: local
  vars: 
    COURSE: ansible
    DURATION: 10HR
    TRAINER: siva
  tasks:
    - name: print course information
      ansible.builtin.debug:
      msg: "Hello {{COURSE}},course duration {{DURATION}}, Trainer {{TRAINER}}"