- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,suresh,joseph,rahim"
  tasks:
    - name: check undefined variable
      ansible.builtin.debug:
        msg: "hello, {{ person | default ('Ramesh')}}"
    - name: print names
      ansible.builtin.debug:
        msg: "hello {{ persons | split(',') }}"
    - name: convert map into list
      vars:
        course:
          name: ansible
          duration: 10hr
          trainer: sivakumar
      ansible.builtin.debug:
        msg: "courseinfo : {{ course | dict2items }}"
    - name: convert list into map
      vars:
        course:
          - { 'key': 'name', 'value': 'ansible'}
          - { 'key': 'duration', 'value': '10hr'}
          - { 'key': 'trainer', 'value': 'sivakumar'}
      ansible.builtin.debug:
        msg: "courseinfo: {{ course | items2dict }}"
    - name: convert to uppercase
      vars:
        name: nirosha
      ansible.builtin.debug:
        msg: "hello {{name | upper }}"
    - name : check ip add is valid or not 
      vars:
        ip: 300.567.980.789
      ansible.builtin.debug:
        msg: "{{ ip | ansible.utils.ipaddr }}"