- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,suresh,joseph,rahim"
  tasks:
    - name: check undefined variable
      ansible.builtin.debug:
        msg: "hello, {{ person | default ('Ramesh')}}"
    - name: print names
      ansible.builtin.debug:
        msg: "hello {{ persons | split(',') }}"
    - name: convert map into list
      vars:
        course:
          name: ansible
          duration: 10hr
          trainer: sivakumar
      ansible.builtin.debug:
        msg: "courseinfo : {{ course | dict2items }}"